# Generated by Django 2.1.1 on 2019-07-22 03:01

import apps.users.models.profiles
import apps.users.validators
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewee', models.CharField(default='ifyouseethisusernamesomethingisverybroken', max_length=45, validators=[apps.users.validators.TouchbaseUsernameValidator()])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('interest_tags_viewee', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('All', 'All'), ('3D printing', '3D printing'), ('Acting', 'Acting'), ('Art', 'Art'), ('Astrology', 'Astrology'), ('Astronomy', 'Astronomy'), ('Automobiles', 'Automobiles'), ('Business', 'Business'), ('Community', 'Community'), ('Computer programming', 'Computer programming'), ('Cooking', 'Cooking'), ('Couponing', 'Couponing'), ('DIY', 'DIY'), ('Dance', 'Dance'), ('Drawing', 'Drawing'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Film', 'Film'), ('Fitness And Exercise', 'Fitness And Exercise'), ('Gaming', 'Gaming'), ('Gardening', 'Gardening'), ('Graphic Design', 'Graphic Design'), ('Hiking', 'Hiking'), ('History', 'History'), ('Magic', 'Magic'), ('Mathematics', 'Mathematics'), ('Music', 'Music'), ('Painting', 'Painting'), ('Pets', 'Pets'), ('Philosophy', 'Philosophy'), ('Photography', 'Photography'), ('Playing musical instruments', 'Playing musical instruments'), ('Politics', 'Politics'), ('Programming', 'Programming'), ('Reading', 'Reading'), ('Role-play', 'Role-play'), ('Science', 'Science'), ('Singing', 'Singing'), ('Sports', 'Sports'), ('Stand-up comedy', 'Stand-up comedy'), ('Vacation', 'Vacation'), ('Writing', 'Writing')], default='', max_length=32), default=apps.users.models.profiles.get_it_default, size=None)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('page', models.CharField(default='Home', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
