# Generated by Django 2.1.1 on 2019-08-03 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilevisit',
            name='viewee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewees', to=settings.AUTH_USER_MODEL),
        ),
    ]
