# Generated by Django 2.1.1 on 2019-01-15 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToushItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_toush_profile', models.BooleanField(default=False)),
                ('is_toush_feed', models.BooleanField(default=False)),
                ('is_toush_events', models.BooleanField(default=False)),
                ('toush_string', models.CharField(default='', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registered at')),
                ('username', models.BooleanField(default=False)),
                ('first_name', models.BooleanField(default=False)),
                ('last_name', models.BooleanField(default=False)),
                ('profile_picture', models.BooleanField(default=False)),
                ('banner', models.BooleanField(default=False)),
                ('color_scheme', models.BooleanField(default=False)),
                ('contact_phone', models.BooleanField(default=False)),
                ('contact_email', models.BooleanField(default=False)),
                ('message', models.CharField(default='', max_length=128)),
                ('link_to_profile', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toush_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToushLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.CharField(max_length=256)),
                ('short_url', models.CharField(db_index=True, max_length=50, unique=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('max_count', models.IntegerField(default=-1)),
                ('lifespan', models.IntegerField(default=-1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expired', models.DateTimeField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toush_link', to='links.ToushItem')),
            ],
        ),
    ]
