# Generated by Django 2.1.1 on 2019-01-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toushitem',
            name='message',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
