# Generated by Django 2.1.1 on 2019-01-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20190116_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toushitem',
            name='toush_string',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
