# Generated by Django 2.1.1 on 2019-01-17 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0003_auto_20190116_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ip_addr_v4', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('ip_addr_v6', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6')),
                ('is_mobile', models.NullBooleanField(default=None)),
                ('is_tablet', models.NullBooleanField(default=None)),
                ('is_touch_capable', models.NullBooleanField(default=None)),
                ('is_pc', models.NullBooleanField(default=None)),
                ('is_bot', models.NullBooleanField(default=None)),
                ('browser', models.CharField(blank=True, default='', max_length=64)),
                ('browser_version', models.CharField(blank=True, default='', max_length=64)),
                ('os', models.CharField(blank=True, default='', max_length=64)),
                ('os_version', models.CharField(blank=True, default='', max_length=128)),
                ('device', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='toushlink',
            name='full_url',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='visitor',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.ToushLink'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
