# Generated by Django 2.1.1 on 2019-01-19 17:21

import apps.links.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20190117_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='toushitem',
            name='profile_items_layout',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=apps.links.models.get_accounts_default),
        ),
    ]
