# Generated by Django 2.1.1 on 2019-01-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_toushitem_profile_items_layout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toushitem',
            old_name='profile_items_layout',
            new_name='accounts_list',
        ),
    ]
