# Generated by Django 2.1.1 on 2019-01-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181230_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, default='', max_length=100),
        ),
    ]
