# Generated by Django 2.1.1 on 2019-01-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190104_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, default='http://touchbase.id', max_length=100),
        ),
    ]
