# Generated by Django 2.1.1 on 2019-01-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190104_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='toush_default_lifespan',
            field=models.IntegerField(default=86400),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='toush_default_max_uses',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='toush_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='toush_max_concurrent_links',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='toush_max_links',
            field=models.IntegerField(default=-1),
        ),
    ]
