# Generated by Django 2.1.1 on 2019-03-28 01:47

import apps.users.models.profiles
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190111_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interest_tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=apps.users.models.profiles.get_it_default),
        ),
    ]
