# Generated by Django 2.1.1 on 2019-04-17 23:16

import apps.users.models.oauth
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_haspspf'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('service', models.CharField(default='', max_length=100)),
                ('pdj', django.contrib.postgres.fields.jsonb.JSONField(default=apps.users.models.oauth.get_pdj_default)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OAuthPosts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
