# Generated by Django 2.1.1 on 2019-04-19 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_globalspflid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalSPFLID',
        ),
    ]
