# Generated by Django 2.1.1 on 2019-04-19 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_globalspflid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPFServiceID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.CharField(default='', max_length=200)),
                ('soundcloud', models.CharField(default='', max_length=200)),
                ('reddit', models.CharField(default='', max_length=200)),
                ('pinterest', models.CharField(default='', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
