# Generated by Django 2.1.1 on 2019-04-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_spfserviceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spfserviceid',
            name='pinterest',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='spfserviceid',
            name='reddit',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='spfserviceid',
            name='soundcloud',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='spfserviceid',
            name='youtube',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
