# Generated by Django 2.1.1 on 2019-07-01 01:39

import apps.users.models.profiles
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190603_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interest_tags_two',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=32), default=apps.users.models.profiles.get_it_default, size=None),
        ),
    ]
