# Generated by Django 2.1.1 on 2019-07-01 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userprofile_interest_tags_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='interest_tags',
        ),
    ]
