# Generated by Django 2.1.1 on 2019-07-01 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_userprofile_interest_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='interest_tags_two',
            new_name='interest_tags',
        ),
    ]
