# Generated by Django 2.1.1 on 2019-07-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190701_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='spfserviceid',
            name='steam',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
