# Generated by Django 2.1.1 on 2019-09-30 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20190903_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='A country on earth', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='A country on earth', max_length=64),
        ),
    ]
