# Generated by Django 2.1.1 on 2019-10-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20190930_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(blank=True, default='https://i.imgur.com/J722HW1.png', verbose_name='profile_pic'),
        ),
    ]
