# Generated by Django 2.1.1 on 2019-10-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20191016_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(default='https://tbdev.nyc3.cdn.digitaloceanspaces.com/m/blank-face.png', verbose_name='profile_pic'),
        ),
    ]
