# Generated by Django 2.1.1 on 2019-08-29 02:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('caption', models.CharField(default='', max_length=100)),
                ('thumbnail', models.CharField(default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(related_name='cliques', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
