# Generated by Django 2.1.1 on 2019-08-29 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clique',
            name='founder',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, related_name='founded_cliques', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
