# Generated by Django 2.1.1 on 2019-09-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliques', '0003_clique_clique_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='clique',
            name='tra_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clique',
            name='tri_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clique',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
