# Generated by Django 2.1.1 on 2019-04-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='s_spf',
            field=models.BooleanField(default=True),
        ),
    ]
