# Generated by Django 2.1.1 on 2019-05-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='billing_email',
            field=models.EmailField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
