# Generated by Django 2.1.1 on 2019-07-22 03:01

import apps.tcss.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TCSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('wtf', django.contrib.postgres.fields.jsonb.JSONField(default=apps.tcss.models.get_follow_default)),
                ('exp', django.contrib.postgres.fields.jsonb.JSONField(default=apps.tcss.models.get_explore_default)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tcss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
