# Generated by Django 2.1.1 on 2019-07-22 23:16

import apps.tcss.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcss',
            name='exp',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=apps.tcss.models.get_explore_default, null=True),
        ),
        migrations.AlterField(
            model_name='tcss',
            name='wtf',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=apps.tcss.models.get_follow_default, null=True),
        ),
    ]
